name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build docker image
        run: docker build . -t airflow:${{ github.sha }}

      - name: Run tests
        run: docker run --rm airflow:${{ github.sha }} bash -c "airflow db init && pytest -v tests"
